# Assignment of variables

In [1]:
# This line is a comment
"""
This block is a LONG COMMENT. It's bounded
between triple quote marks.
As many lines as you want.
"""

mass = 36.12 # real num. (float)
gravity = 9.81 # another real num.
jas = 32 # integer
alpha = 2 + 3j # complex num.
beta = complex(2, 3) # alt. of defining complex num.
my_name = "Sandy Herho" # alphanum. string

# Assignment of lists, dictionaries, and tuples

In [2]:
# lists
primes = [2, 3, 5, 7, 11, 13]

days = ['monday', 'tuesday', 'friday']

movies = [
    ["Star Wars", 1977],
    ["Superman II", 1980],
    ["Gremlins", 1984],
    ["Schlinder's list", 1993]
]

# dictionaries
my_dict = {
    "Marinir":"AL",
    "Kostrad":"AD",
    "Pasgat":"AU"
}

# tuples - lists with fixed contents (can't be modified)
tup1 = ('A', 'b', 1, 2)
tup2 = (1,2,3)

In [3]:
# Arrays
import numpy as np

vec = np.array([1, 4, 6])
print(vec)
print('\n')

# col. array
vec_col = vec.reshape(-1,1)
print(vec_col)
print('\n')

# col. array more visual
vec_col2 = np.array([
    [1],
    [2],
    [3]
])
print(vec_col2)
print('\n')

# matrix
mat = np.array([[1,2,3],
               [4,5,6],
               [7,8,9]])
print(mat)

[1 4 6]


[[1]
 [4]
 [6]]


[[1]
 [2]
 [3]]


[[1 2 3]
 [4 5 6]
 [7 8 9]]


# Calculations and ops

In [4]:
force = mass * gravity
print(force)
print('\n')

alpha = np.log(np.sin(np.pi*gravity)**2) - .5
print(alpha)
print('\n')

ux3 = np.pi * np.sin(alpha) * np.e
print(ux3)
print('\n')

vec2 = vec + vec
print(vec)
print(vec2)
print('\n')

vec3 = vec * vec
print(vec3)
print('\n')

dot = np.dot(vec, vec)
print(dot)
print('\n')

mat2 = np.dot(mat, mat)
print(mat)
print(mat2)
print('\n')

Au = np.linalg.eigvals(mat)
print(Au)
print('\n')

test = "Halo " + "nama saya: " + my_name
print(test)

354.3372


-1.6522101618501746


-8.511448264906445


[1 4 6]
[ 2  8 12]


[ 1 16 36]


53


[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[ 30  36  42]
 [ 66  81  96]
 [102 126 150]]


[ 1.61168440e+01 -1.11684397e+00 -3.38433605e-16]


Halo nama saya: Sandy Herho


# Extract data from arrays

In [15]:
print(vec)
print('\n')

aa = vec[2] # extract the 3rd value from an array
print(aa)
print('\n')

bb = vec[:2] # extract the 1st and 2nd vals.
print(bb)
print('\n')

cc = vec[:] # extract all vals.
print(cc)
print('\n')

mat1

[1 4 6]


6


[1 4]


[1 4 6]


